version: '3.8'

services:
  server:
    image: openjdk:17-oracle
    container_name: server
    volumes:
      - ./pet-store-course-work-1.0-SNAPSHOT.jar:/app.jar
    command: java -jar app.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ZooShop
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ZooShop
    volumes:
      - ./data_db:/var/lib/postgresql/data
      - ./initsql:/docker-entrypoint-initdb.d
